"ui.background" = { fg = "fg", bg = "bg" }
"ui.text" = { fg = "fg", bg = "bg" }
"ui.virtual.whitespace" = { fg = "grey10" }
"ui.cursorline" = { bg = "grey7" }
"ui.cursorcolumn" = { bg = "grey7" }
"ui.linenr" = { fg = "comment" }
"ui.popup" = { bg = "bgFloat" }
"ui.virtual.ruler" = { bg = "grey5" }
"ui.cursor" = { bg = "cursor", fg = "bg" }
"ui.cursor.match" = { bg = "punctuation", fg = "bg" }
"ui.text.focus" = { fg = "keyword" }
"error" = { fg = "error" }
"ui.window" = { fg = "grey30" }
"ui.gutter" = { fg = "fg", bg = "bg" }
"ui.statusline" = { fg = "fg", bg = "bg" }
"ui.menu" = { bg = "bgFloat" }
"ui.menu.selected" = { bg = "selection" }
"ui.menu.scroll" = { fg = "punctuation", bg = "grey5" }
"ui.bufferline" = { bg = "shade3", fg = "shade30" }
"ui.bufferline.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "shade10", underline = { style = "line" } }
"ui.selection" = { bg = "selection" }
"warning" = { fg = "warning" }
"constant.character" = { fg = "attribute" }
"constant.numeric" = { fg = "number" }
"constant.builtin.boolean" = { fg = "keyword" }
"function.method" = { fg = "method" }
"variable.other.member" = { fg = "property" }
"keyword.operator" = { fg = "punctuation" }
"function.special" = { fg = "keyword" }
"special" = { fg = "attribute" }
"info" = { fg = "info" }
"hint" = { fg = "hint" }
"diagnostic.hint" = { fg = "hint" }
"diagnostic.error" = { fg = "error" }
"diagnostic.warning" = { fg = "warning" }
"diagnostic.info" = { fg = "info" }


"constructor" = { fg = "type" }
"operator" = { fg = "punctuation" }
"punctuation" = { fg = "punctuation" }
"punctuation.bracket" = { fg = "punctuation" }
"punctuation.delimiter" = { fg = "punctuation" }
"punctuation.special" = { fg = "punctuation" }
"symbol" = { fg = "constant" }
"constant" = { fg = "constant" }
"constant.builtin" = { fg = "keyword" }
"comment" = { fg = "comment" }
"string.escape" = { fg = "attribute" }
"method" = { fg = "method" }
"function" = { fg = "method" }
"function.call" = { fg = "method" }
"function.builtin" = { fg = "method" }
"parameter" = { fg = "parameter" }
"field" = { fg = "property" }
"property" = { fg = "property" }
"label" = { fg = "label" }
"type" = { fg = "type" }
"type.builtin" = { fg = "keyword" }
"type.qualifier" = { fg = "keyword" }
"keyword" = { fg = "keyword" }
"keyword.modifier" = { fg = "keyword" }
"string" = { fg = "string" }
"namespace" = { fg = "module" }
"number" = { fg = "number" }
"annotation" = { fg = "label" }
"text" = { fg = "fg" }
"text.strong" = { modifiers = ["bold"] }
"text.italic" = { modifiers = ["italic"] }
"text.underline" = { underline = { style = "line" } }
"text.title" = { fg = "keyword" }
"text.literal" = { fg = "property" }
"text.uri" = { fg = "tag", underline = { style = "line" } }
"variable" = { fg = "fg" }
"variable.constant" = { fg = "constant" }
"variable.builtin" = { fg = "keyword" }
"tag" = { fg = "tag" }
"attribute" = { fg = "label" }
"tag.attribute" = { fg = "attribute" }
"variable.parameter" = { fg = "parameter" }
"variable.member" = { fg = "property" }
"module" = { fg = "module" }
"string.special.symbol" = { fg = "constant" }
"markup.strong" = { modifiers = ["bold"] }
"markup.underline" = { underline = { style = "line" } }
"markup.heading" = { fg = "keyword" }
"markup.link.url" = { fg = "tag", underline = { style = "line" } }
"markup.raw" = { fg = "property" }
"markup.list" = { fg = "punctuation" }
"string.special.url" = { fg = "tag", underline = { style = "line" } }

"diff.plus" = { fg = "added" }
"diff.minus" = { fg = "deleted" }
"diff.delta" = { fg = "changed" }

[palette]
white = "#ffffff"
green = "#008200"
bg = "#282C34"
bgFloat = "#21242D"
fg = "#ABB2BF"
cursor = "#FFCC00"
keyword = "#10B1FE"
comment = "#636D83"
punctuation = "#7A82DA"
method = "#3FC56B"
type = "#FF6480"
string = "#F9C859"
number = "#FF78F8"
constant = "#9F7EFE"
tag = "#3691FF"
attribute = "#FF936A"
property = "#CE9887"
parameter = "#8bcdef"
label = "#50acae"
module = "#FF839B"
# workspace
primary = "#3691ff"
selection = "#274670"
search = "#1A7247"
diffAdd = "#105B3D"
diffChange = "#10415B"
diffDelete = "#522E34"
added = "#177F55"
changed = "#1B6E9B"
deleted = "#A14D5B"
diffText = "#10415B"
error = "#ff2e3f"
errorBG = "#FDCFD1"
warning = "#da7a43"
warningBG = "#F2DBCF"
info = "#3691ff"
infoBG = "#D4E3FA"
hint = "#7982DA"
mergeCurrent = "#4B3D3F"
mergeCurrentLabel = "#604B47"
mergeIncoming = "#2F476B"
mergeIncomingLabel = "#305C95"
mergeParent = "#EB1C20"
mergeParentLabel = "#EB1D29"
# terminal
terminalBlack = "#42444d"
terminalRed = "#fc2e51"
terminalGreen = "#25a45c"
terminalYellow = "#ff9369"
terminalBlue = "#3375fe"
terminalMagenta = "#9f7efe"
terminalCyan = "#4483aa"
terminalWhite = "#cdd3e0"
terminalBrightBlack = "#8f9aae"
terminalBrightRed = "#ff637f"
terminalBrightGreen = "#3fc56a"
terminalBrightYellow = "#f9c858"
terminalBrightBlue = "#10b0fe"
terminalBrightMagenta = "#ff78f8"
terminalBrightCyan = "#5fb9bc"
terminalBrightWhite = "#ffffff"
rainbowRed = "#FF6666"
rainbowYellow = "#f4ff78"
rainbowBlue = "#44A5FF"
rainbowOrange = "#ffa023"
rainbowGreen = "#92f535"
rainbowViolet = "#ff78ff"
rainbowCyan = "#28e4eb"

shade1 = "#2A2E37"
shade2 = "#2C313A"
shade3 = "#2C313A"
shade4 = "#2F333D"
shade5 = "#31363F"
shade6 = "#333842"
shade7 = "#353B45"
shade8 = "#373D48"
shade9 = "#373D48"
shade10 = "#3A3F4B"
shade20 = "#4B5362"
shade25 = "#575F70"
shade30 = "#5F697C"
shade40 = "#727D92"
shade50 = "#8992A4"
shade60 = "#A0A7B6"
shade70 = "#B7BCC8"
shade80 = "#D1D4DC"
shade90 = "#E8EAED"

grey3 = "#2C33F0"
grey5 = "#333B48"
grey7 = "#384252"
grey10 = "#3C485D"
grey20 = "#4A5A73"
grey25 = "#526380"
grey30 = "#5A6E8C"
grey40 = "#687FA1"
