"ui.background" = { fg = "fg", bg = "bg" }
"ui.text" = { fg = "fg"}
"ui.text.focus" = {fg = "cursor"}
"ui.virtual.whitespace" = { fg = "grey10" }
"ui.cursorline" = { bg = "grey7" }
"ui.cursorcolumn" = { bg = "grey7" }
"ui.virtual.inlay-hint" = {bg = "shade3", fg = "shade25"}
"ui.virtual.jump-label" = {fg = "cursor", modifiers = ["bold"]}
"ui.linenr" = { fg = "comment" }
"ui.popup" = { bg = "bgFloat" }
"ui.virtual.ruler" = { bg = "grey5" }
"ui.cursor" = { bg = "cursor", fg = "bg" }
"ui.cursor.match" = { bg = "punctuation", fg = "bg" }
"ui.highlight" = {bg = "selection"}
"error" = { fg = "error" }
"ui.window" = { fg = "grey30" }
"ui.gutter" = { fg = "fg", bg = "bg" }
"ui.statusline" = { fg = "fg", bg = "bg" }
"ui.menu" = { bg = "bgFloat" }
"ui.menu.selected" = { bg = "selection" }
"ui.menu.scroll" = { fg = "punctuation", bg = "grey5" }
"ui.bufferline" = { bg = "shade3", fg = "shade30" }
"ui.bufferline.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "shade10", underline = { style = "line" } }
"ui.selection" = { bg = "selection" }
"warning" = { fg = "warning" }
"constant.character" = { fg = "attribute" }
"constant.numeric" = { fg = "number" }
"constant.builtin.boolean" = { fg = "keyword" }
"function.method" = { fg = "method" }
"variable.other.member" = { fg = "property" }
"keyword.operator" = { fg = "punctuation" }
"function.special" = { fg = "keyword" }
"special" = { fg = "attribute" }
"info" = { fg = "info" }
"hint" = { fg = "hint" }
"diagnostic.hint" = { fg = "hint" }
"diagnostic.error" = { fg = "error" }
"diagnostic.warning" = { fg = "warning" }
"diagnostic.info" = { fg = "info" }

"constructor" = { fg = "type" }
"operator" = { fg = "punctuation" }
"punctuation" = { fg = "punctuation" }
"punctuation.bracket" = { fg = "punctuation" }
"punctuation.delimiter" = { fg = "punctuation" }
"punctuation.special" = { fg = "punctuation" }
"symbol" = { fg = "constant" }
"constant" = { fg = "constant" }
"constant.builtin" = { fg = "keyword" }
"comment" = { fg = "comment" }
"string.escape" = { fg = "attribute" }
"method" = { fg = "method" }
"function" = { fg = "method" }
"function.call" = { fg = "method" }
"function.builtin" = { fg = "method" }
"parameter" = { fg = "parameter" }
"field" = { fg = "property" }
"property" = { fg = "property" }
"label" = { fg = "label" }
"type" = { fg = "type" }
"type.builtin" = { fg = "keyword" }
"type.qualifier" = { fg = "keyword" }
"keyword" = { fg = "keyword" }
"keyword.modifier" = { fg = "keyword" }
"string" = { fg = "string" }
"namespace" = { fg = "module" }
"number" = { fg = "number" }
"annotation" = { fg = "label" }
"text" = { fg = "fg" }
"text.strong" = { modifiers = ["bold"] }
"text.italic" = { modifiers = ["italic"] }
"text.underline" = { underline = { style = "line" } }
"text.title" = { fg = "keyword" }
"text.literal" = { fg = "property" }
"text.uri" = { fg = "tag", underline = { style = "line" } }
"variable" = { fg = "fg" }
"variable.constant" = { fg = "constant" }
"variable.builtin" = { fg = "keyword" }
"tag" = { fg = "tag" }
"attribute" = { fg = "label" }
"tag.attribute" = { fg = "attribute" }
"variable.parameter" = { fg = "parameter" }
"variable.member" = { fg = "property" }
"module" = { fg = "module" }
"string.special.symbol" = { fg = "constant" }
"markup.strong" = { modifiers = ["bold"] }
"markup.underline" = { underline = { style = "line" } }
"markup.heading" = { fg = "keyword" }
"markup.link.url" = { fg = "tag", underline = { style = "line" } }
"markup.raw" = { fg = "property" }
"markup.list" = { fg = "punctuation" }
"string.special.url" = { fg = "tag", underline = { style = "line" } }

"diff.plus" = { fg = "added" }
"diff.minus" = { fg = "deleted" }
"diff.delta" = { fg = "changed" }

[palette]
bg = "#F9F9F9"
bgFloat = "#ECEDEE"
fg = "#383A42"
cursor = "#F31459"
keyword = "#0098DD"
comment = "#A0A1A7"
punctuation = "#7A82DA"
method = "#23974A"
type = "#D52753"
string = "#C5A332"
number = "#CE33C0"
constant = "#823FF1"
tag = "#275FE4"
attribute = "#DF631C"
property = "#A05A48"
parameter = "#40B8C5"
label = "#047485"
module = "#ee5672"
primary = "#0099e1"
selection = "#d2ecff"
search = "#b1eacf"
diffAdd = "#c5f6c8"
diffChange = "#C2E4FF"
diffDelete = "#fac1c6"
added = "#3cbc66"
changed = "#0099e1"
deleted = "#FA7883"
diffText = "#C2E4FF"
error = "#ff0000"
errorBG = "#FCE4E4"
warning = "#ff8f3a"
warningBG = "#FBE4D5"
info = "#0099e1"
infoBG = "#D2ECFF"
hint = "#7982DA"

shade3 = "#F2F2F2"
shade10 = "#E0E0E0"
shade25 = "#575F70"
shade30 = "#B0B0B0"

grey5 = "#E7E8E9"
grey7 = "#DEE1E3"
grey10 = "#D2D8DA"
grey30 = "#A2AEB3"
